### ISSUE TITLE
Verify that step expressions are interpreted according to spec

### ISSUE THREAD

**Issue by tituomin** [markusand/mapboxgl-legend#13]
When interpreting numeric step expressions for colors, we are currently using the "other" label for the base color (stop_output_0 in the spec). 

However, it looks to me that there should be some label like `< [first step]`. Also, this label should be ordered accordingly as the first label since it's numerically the first one also.

https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#step

I could just override the "other" label in the metadata, but it would be nice if the label automatically incorporated the value of the first step, and also it should be the first label and not the last. For example if the first step is 5, it would read `< 5`.
(Btw, I'm working in a non-English, multilingual context so something like `up to 5` would be suboptimal)

It could even read "0-5" if we knew the minimum value in the data was 0, but I realize this might be out of scope.

I'm happy to implement at least a minimal "< [first step]" version if you agree this is needed.

**Comment by markusand** [comment]
I've been also using the workaround of overriding the `other` label, but having this natively makes total sense to me. Certainly it would be weird to have the `< 5` label at the end.

I'm also in a non english context and I absolutely agree to prevent all wording. That's why I'm using `+5`-like labels. I'm thinking that `+5` should be changed to `> 5` as well to keep consistency in labeling.

**Comment by markusand** [comment]
Fix published with v1.7.2
