### ISSUE TITLE
using npm i has bundled library

### ISSUE THREAD

**Issue by shitathakin** [markusand/mapboxgl-legend#7]
When i download the module, i get .min.js files that are bundled. Thus unusable. Can anyone help?

**Comment by shitathakin** [comment]
I get this in the console.
```
ERROR in ./node_modules/mapboxgl-legend/dist/index.esm.min.js 1:7893
Module parse failed: Unexpected token (1:7893)
```
and in the code it says i have a ts7016. 
Do i need loaders or something to use this module?

**Comment by markusand** [comment]
If you use npm to install modules it is implicit you're going to bundle them with Webpack, Rollup or any other bundler. Otherwise, you better load the library from a CDN.

Documentation on how to install the module and load it in https://github.com/markusand/mapboxgl-legend#get-started

If you still want to load the script directly from the installed module, you can find an example in https://github.com/markusand/mapboxgl-legend/blob/master/examples/index.html.
**Atention! This requires to use a local web server to avoid CORS on loading scripts**

If you're just creating an HTML file with all embedded javascript, the simplest, straightforward and recommended way is to forget about npm and load the library directly from a CDN, the same way you are loading with mapbox-gl.
```html
<head>
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.0.0/mapbox-gl.js"></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.0.0/mapbox-gl.css" rel="stylesheet" />
    <script src="https://unpkg.com/mapboxgl-legend@1.4.2/dist/index.umd.min.js"></script>
    <link href="https://unpkg.com/mapboxgl-legend@1.4.2/dist/index.umd.min.css" rel="stylesheet" />
</head>
```

By the way, **never EVER** include `node_modules` to your [git repository](https://github.com/hiroshimaeasyryo/map_project). Use `.gitignore`

**Comment by markusand** [comment]
I suggest loading the library directly from the CDN. You already do it with mapbox, no need to hassle with all the bundler boilerplate for no reason.

**Comment by shitathakin** [comment]
Works perfectly from CDN. Great library Mark.
